# Generated by Django 3.1.2 on 2020-10-18 22:11

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncerrarPartida',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bolao.partida',),
        ),
        migrations.AddField(
            model_name='partida',
            name='partida_encerrada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='partida',
            name='nome_time1',
            field=models.CharField(max_length=100, verbose_name='Time 1'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='nome_time2',
            field=models.CharField(max_length=100, verbose_name='Time 2'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='placar_time1',
            field=models.IntegerField(default=0, verbose_name='Placar Time 1'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='placar_time2',
            field=models.IntegerField(default=0, verbose_name='Placar Time 2'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='login_player',
            field=models.CharField(max_length=50, unique=True, verbose_name='Login'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome_player',
            field=models.CharField(max_length=200, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='saldo_player',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='BRL', max_digits=10, verbose_name='Saldo'),
        ),
    ]
